### ISSUE TITLE
Check if permision is granted

### ISSUE THREAD

**Issue by webserveis** [pankaj89/PermissionHelper#1]
How to check if you have been granted or denied when next operation?

Or, if it is already granted, it is launched again

```
    public void onPermissionGranted() {
        Log.d(TAG, "onPermissionGranted() called");
    }
```
Every time you ask to check your status

**Comment by pankaj89** [comment]
Hello,
When user already granted permission then onPermissionGranted() method will be called, without asking for any permission dialog, so you don't need to check it user already granted permission or not, simply write a code inside onPermissionGranted() method, 

So Flow will be if User didn't grant permission it will open permission dialog and call onPermissionGranted() method if User already granted permission then also onPermissionGranted() method will be fired.
