### ISSUE TITLE
Kotlin : understanding request actions and callbacks

### ISSUE THREAD

**Issue by Awsom3D** [pankaj89/PermissionHelper#10]
Hi there, 

I'm migrating from java to kt, and I'm having a hard time understanding your Kotlin example

In Java, the callbacks are embedded in the request() method. 

In Kotlin, there is several callback setup (requestAll / denied / requestIndividual )
Does setting any callback does the request action ? What method does ?
Should I call requestAll ? There is no usage example in the README of this method and I don't understand why I must setup callbacks as arguments to requestAll since I set up these callbacks before.

Thank you for your clarifications.

**Comment by pankaj89** [comment]
Hi,

You can find example in main readme file https://github.com/pankaj89/PermissionHelper
```
permissionHelper = PermissionHelper(this, arrayOf(Manifest.permission.CAMERA, Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.CALL_PHONE), 100)
permissionHelper?.denied {
    if (it) {
        Log.d(TAG, "Permission denied by system")
        permissionHelper?.openAppDetailsActivity()
    } else {
        Log.d(TAG, "Permission denied")
    }
}

//Request all permission
permissionHelper?.requestAll {
    Log.d(TAG, "All permission granted")
}

//Request individual permission
permissionHelper?.requestIndividual {
    Log.d(TAG, "Individual Permission Granted")
}
```

**Comment by Awsom3D** [comment]
Hi, thank you, but that's exactly this example that I don't understand : 

does denied ask for permissions ?
does requestAll ask for permissions ? 
does requestIndividual ask for permissions ?

They all looks like callbacks to me. No actual requests.

**Comment by pankaj89** [comment]
Okay let me explain it, basically all are request and gives callback on same location, 

1. 
```
permissionHelper?.denied {
    if (it) {
        Log.d(TAG, "Permission denied by system")
        permissionHelper?.openAppDetailsActivity()
    } else {
        Log.d(TAG, "Permission denied")
    }
}
```
This will attach a callback which will be called when permission is denied, inside it there will be one param it which is boolean states whether this denied is user derived or system derived(Permanently denied).

2.
```
permissionHelper?.requestAll {
    Log.d(TAG, "All permission granted")
}
```
This will request All permission to be grantended and attach callback on same place. we use this method when we require all permission to be granted by user.

3.
```
permissionHelper?.requestIndividual {
    Log.d(TAG, "Individual Permission Granted")
}
```
This method start requesting permission with callback, we use this method when we are OK to proceed with some permission granted.

On onRequestPermissionsResult() call 
```
permissionHelper.onRequestPermissionsResult(requestCode, permissions, grantResults);
```

**Comment by Awsom3D** [comment]
Thank you, I guess I was confused by denied() being a callback not doing any actual request, and I thought that the other methods were callbacks as well, with requestAll maybe calling requestIndividual (as a callback) in case user gave partial permissions.

So if I want all permissions : requestAll() 
Or, if I want only some permissions : requestIndividual() 
And if I do not get what I want with any of these methods : denied() will be called.

Thanks a lot !
