### ISSUE TITLE
jcenter() deprecation and failed build after removing jcenter()

### ISSUE THREAD

**Issue by Sharprender** [pankaj89/PermissionHelper#11]
I've installed Android Studio and now jcenter() in build.gradleis shown as deprecated.

Here is the article from developer.android.com:
[https://developer.android.com/studio/build/jcenter-migration](url)

If I remove jcenter() from my build.gradle file, I can not build anymore, because permissionhelper dependency can't be resolved.

Is a migration to other repositories like mavenCentral or something else planned?

**Comment by pankaj89** [comment]
Hi @Sharprender Will migrate it to another repo today.

Thanks.

**Comment by Sharprender** [comment]
Well done. Now build is working again.
Thanks!
