### ISSUE TITLE
Conflict android:allowBackup

### ISSUE THREAD

**Issue by andrian1311** [pankaj89/PermissionHelper#3]
I can't set `android:allowBackup = false` without add `tools:replace = "android:allowBackup"` because Your PermissionHelper library has `android:allowBackup = true` in **AndroidManifest.xml**

I don't think in PermissionHelper library need `android:allowBackup = true` so it should be removed from AndroidManifest.xml file, otherwise it will conflict if I implement allowBackup = false in my App

**Comment by pankaj89** [comment]
Problem is solved, now you can use 1.2 version as 
```
compile 'com.master.android:permissionhelper:1.2'
```
