### ISSUE TITLE
Posible incosistent work on hasPermission?

### ISSUE THREAD

**Issue by webserveis** [pankaj89/PermissionHelper#5]
init
`permissionHelper = new PermissionHelper(this, new String[]{Manifest.permission.READ_CONTACTS}, PERM_READ_CONTACT);`

Call permission 
`permissionHelper.request(this);`

And chosse DENIED option

when consult if permission is GRANTED or DENIED with `hasPermission` in other process function.
I am not sure if it serves this purpose

`permissionHelper.hasPermission(Manifest.permission.READ_CONTACTS)`

return TRUE

I need to use:
`if (ContextCompat.checkSelfPermission(this, Manifest.permission.READ_CONTACTS) != PackageManager.PERMISSION_GRANTED)` 

Mmm or it works fine but I have misunderstood its functionality

**Comment by pankaj89** [comment]
Hello, @webserveis 
With 
```
compile 'com.master.android:permissionhelper:1.4'
```
hasPermission() method is private now and renamed to hasPermissionInManifest()
