### ISSUE TITLE
What is the usage for `onRequestPermissionsResult`?

### ISSUE THREAD

**Issue by kenchoong** [pankaj89/PermissionHelper#6]
Hey just checking in.

What is the usage for `onRequestPermissionResult`? Does it necessary to add to every fragment or activity that request permission?

**Comment by pankaj89** [comment]
Yes, 
You  need to override this method to handle permission request response
For more information regarding handing by your own
https://developer.android.com/training/permissions/requesting#handle-response

**Comment by kenchoong** [comment]
ok noted..thanks
