### ISSUE TITLE
Old android support libraries still in use, blocking us from disabling jetifier

### ISSUE THREAD

**Issue by carstenhag** [pankaj89/PermissionHelper#7]
Hello there, we are using your lib for quite a while now, and it's been working great, so thanks for that! 😄.

I tried out to remove jetifier in order to get faster speeds, but many libraries are stll using the old support libraries. The same applies to your lib. `PermissionHelper` and `PermissionHelperJava` are the files where https://github.com/dipien/bye-bye-jetifier complains at.

**Comment by carstenhag** [comment]
I have created a Pull Request for this :) See #8. 

FYI @pankaj89

**Comment by carstenhag** [comment]
@pankaj89 thanks a lot for merging :). Can you please also create a new release? After that's done, I'll close this ticket.

**Comment by pankaj89** [comment]
Very sorry for delay, but here's new release
`implementation 'com.master.android:permissionhelper:2.2'`

**Comment by carstenhag** [comment]
Thanks a lot for the release :). I will close this ticket.
